# Set for Ubuntu 17.04 arm toolchain
# install with sudo apt-get install gcc-arm-linux-gnueabi qemu-user

target = "arm-linux-gnueabi"

[toolchain]
cc = "arm-linux-gnueabi-gcc"
cflags = "-march=armv7-a -marm"
ldflags = "-static"

[[libdir]]
dir = "$C2_LIBDIR"

[output]
dir = "output_arm"
